<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Forwarder.Rung3.Linux</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Forwarder.Core\Forwarder.Core.csproj" />
  </ItemGroup>
</Project>
